apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: loki
    chart: loki-2.16.0
    release: {{ default "loki-stack" .Values.loki.name }}
    heritage: Helm
  annotations:
    {}
  name: {{ default "loki-stack" .Values.loki.name }}
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: true
imagePullSecrets:
  - name: turaco-harbor-registry
---
# Source: loki-stack/charts/loki/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ default "loki-stack" .Values.loki.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: loki
    chart: loki-2.16.0
    release: {{ default "loki-stack" .Values.loki.name }}
    heritage: Helm
data:
  loki.yaml: {{ .Values.loki.config }}
---
# Source: loki-stack/charts/loki/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ default "loki-stack" .Values.loki.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: loki
    chart: loki-2.16.0
    release: {{ default "loki-stack" .Values.loki.name }}
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ default "loki-stack" .Values.loki.name }}
subjects:
- kind: ServiceAccount
  name: {{ default "loki-stack" .Values.loki.name }}
---
# Source: loki-stack/charts/loki/templates/service-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ default "loki-stack" .Values.loki.name }}-headless
  namespace: {{ .Values.namespace }}
  labels:
    app: loki
    chart: loki-2.16.0
    release: {{ default "loki-stack" .Values.loki.name }}
    heritage: Helm
    variant: headless
spec:
  clusterIP: None
  ports:
    - port: 3100
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    app: loki
    release: {{ default "loki-stack" .Values.loki.name }}
---
# Source: loki-stack/charts/loki/templates/service-memberlist.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ default "loki-stack" .Values.loki.name }}-memberlist
  namespace: {{ .Values.namespace }}
  labels:
    app: loki
    chart: loki-2.16.0
    release: {{ default "loki-stack" .Values.loki.name }}
    heritage: Helm
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 7946
      targetPort: memberlist-port
      protocol: TCP
  selector:
    app: loki
    release: {{ default "loki-stack" .Values.loki.name }}
---
# Source: loki-stack/charts/loki/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ default "loki-stack" .Values.loki.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: loki
    chart: loki-2.16.0
    release: {{ default "loki-stack" .Values.loki.name }}
    heritage: Helm
  annotations:
    {}
spec:
  type: ClusterIP
  ports:
    - port: 3100
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    app: loki
    release: {{ default "loki-stack" .Values.loki.name }}
---
# Source: loki-stack/charts/loki/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ default "loki-stack" .Values.loki.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: loki
    turaco-app: {{ default "loki-stack" .Values.loki.name }} 
    chart: loki-2.16.0
    release: {{ default "loki-stack" .Values.loki.name }}
    heritage: Helm
  annotations:
    {}
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: loki
      release: {{ default "loki-stack" .Values.loki.name }}
  serviceName: {{ default "loki-stack" .Values.loki.name }}-headless
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: loki
        turaco-app: {{ default "loki-stack" .Values.loki.name }} 
        name: {{ default "loki-stack" .Values.loki.name }}
        release: {{ default "loki-stack" .Values.loki.name }}
      annotations:
        checksum/config: 4f967088c8b1634add82c93f2fd15868de21fd6a77fc841c48b989e7e403247c
        prometheus.io/port: http-metrics
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: {{ default "loki-stack" .Values.loki.name }}
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      initContainers:
        []
      containers:
        - name: loki
          image: "registry.turacocloud.com/turaco-common/grafana/loki:2.6.1-amd64"
          imagePullPolicy: IfNotPresent
          args:
            - "-config.file=/etc/loki/loki.yaml"
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: config
              mountPath: /etc/loki
            - name: storage
              mountPath: "/data"
              subPath: 
          ports:
            - name: http-metrics
              containerPort: 3100
              protocol: TCP
            - name: grpc
              containerPort: 9095
              protocol: TCP
            - name: memberlist-port
              containerPort: 7946
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
          resources:
            {{- if and (ne .Values.loki.resources.limits.memory "0Mi") (ne .Values.loki.resources.limits.memory "0Gi") }}
            limits:
              memory: {{ .Values.loki.resources.limits.memory }}
              cpu: {{ .Values.loki.resources.limits.cpu }}
            {{- end }}
            requests:
              cpu: {{ .Values.loki.resources.requests.cpu }}
              memory: {{ .Values.loki.resources.requests.memory }}
          securityContext:
            readOnlyRootFilesystem: true
          env:
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []
      terminationGracePeriodSeconds: 4800
      volumes:
        - name: tmp
          emptyDir: {}
        - name: config
          secret:
            secretName: {{ default "loki-stack" .Values.loki.name }}
        - name: storage
          emptyDir: {}
---
