apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.tempo.name }}-config
  labels:
    helm.sh/chart: tempo-distributed-1.2.2
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: turaco
    app.kubernetes.io/version: "2.0.0"
    app.kubernetes.io/managed-by: Helm
  namespace: {{ .Values.namespace }}
data:
  tempo-query.yaml: |
    backend: 127.0.0.1:{{ .Values.tempo.port_number }}
    
  overrides.yaml: |
    
    overrides: {}
    
  tempo.yaml: |
    
    compactor:
      compaction:
        block_retention: 48h
        compacted_block_retention: 1h
        compaction_cycle: 30s
        compaction_window: 1h
        max_block_bytes: 107374182400
        max_compaction_objects: 6000000
        max_time_per_tenant: 5m
        retention_concurrency: 10
        v2_in_buffer_bytes: 5242880
        v2_out_buffer_bytes: 20971520
        v2_prefetch_traces_count: 1000
      ring:
        kvstore:
          store: memberlist
    distributor:
      receivers:
        jaeger:
          protocols:
            grpc:
              endpoint: 0.0.0.0:14250
            thrift_binary:
              endpoint: 0.0.0.0:6832
            thrift_compact:
              endpoint: 0.0.0.0:6831
            thrift_http:
              endpoint: 0.0.0.0:14268
        opencensus:
          endpoint: 0.0.0.0:55678
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
      ring:
        kvstore:
          store: memberlist
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 3
        tokens_file_path: /var/tempo/tokens.json
    memberlist:
      abort_if_cluster_join_fails: false
      join_members:
      - {{ .Values.tempo.name }}-gossip-ring
    multitenancy_enabled: false
    overrides:
      per_tenant_override_config: /conf/overrides.yaml
    querier:
      frontend_worker:
        frontend_address: {{ .Values.tempo.name }}-query-frontend-discovery:9095
      max_concurrent_queries: 20
      search:
        external_endpoints: []
        external_hedge_requests_at: 8s
        external_hedge_requests_up_to: 2
        prefer_self: 10
        query_timeout: 30s
    query_frontend:
      search:
        concurrent_jobs: 1000
        target_bytes_per_job: 104857600
    server:
      grpc_server_max_recv_msg_size: 4194304
      grpc_server_max_send_msg_size: 4194304
      http_listen_port: 3100
      log_format: logfmt
      log_level: info
    storage:
      trace:
        backend: local
        blocklist_poll: 5m
        cache: memcached
        local:
          path: /var/tempo/traces
        memcached:
          consistent_hash: true
          host: tempo-memcached
          service: memcached-client
          timeout: 500ms
        wal:
          path: /var/tempo/wal