service:
  port:
    name: http
    l4_protocol: TCP
    port: 8080
    targetPort: 8080
  label: board-tguhhtgu
  name: board-tguhhtgu
  selector: board-tguhhtgu
  type:
  - ClusterIP
  - NodePort
namespace: -@namespace@-
pvc:
  name: pvc-board-tguhhtgu
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
deployment:
  app:
    name: board-tguhhtgu
    type: springboot
  replicas: -@replicas@-
  update:
    type: RollingUpdate
  repo:
    url: -@imageRepoName@-
  image:
    name: board-tguhhtgu
    tag: lastest
    secret: -@repoSecret@-
  container:
    name: board-tguhhtgu
    port: 8080
  volume:
    name: pvc-board-tguhhtgu
  resource:
    request:
      memory: -@requestMemory@-
      cpu: -@requestCpu@-
    limits:
      memory: -@limitsMemory@-
      cpu: -@limitsCpu@-
  backing: 
    mysql:
      name: secret-board-database-aearptp6
  secret:
    name: []
  configmap:
    name: []
  hpa:
    name: hpa-board-tguhhtgu
    minReplicas: -@minReplicas@-
    maxReplicas: -@maxReplicas@-
    cpu: -@cpuAutoScale@-
    memory: -@memAutoScale@-
