apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default "loki-stack" .Values.grafana.name }}
  namespace: {{ .Values.namespace }}
  labels:
    helm.sh/chart: grafana-6.43.5
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: {{ .Values.grafana.name }}
    app.kubernetes.io/version: "8.3.5"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: turaco
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = ''